# .github/release.yml


changelog:
name-template: 'Aaaah 🌟'
  exclude:
    labels:
      - lib update
categories:
    - title: Refactor 🛠
      labels:
        - refactor
    - title: Bug fix 🐛
      labels:
        - bug-fix
change-template: '- Tarsi -'


      
