# .github/release.yml

changelog:
  exclude:
    labels:
      - lib update
  categories:
    - title: Refactor 🛠
      labels:
        - $LABEL_REFACTOR
    - title: Bug Fix 🎉
      labels:
        - $LABEL_BUGFIX
