# .github/release.yml


changelog:
  exclude:
    labels:
      - lib update
categories:
    - title: Refactor 🛠
      labels:
        - refactor
    - title: Bug fix 🐛
      labels:
        - bug-fix

      
